//
// Account.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Account: JSONEncodable {
    public var peerID: PeerID?
    /** Random sequence number encrypted with the public key of the user.  */
    public var sequenceNumber: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["peerID"] = self.peerID?.encodeToJSON()
        nillableDictionary["sequenceNumber"] = self.sequenceNumber?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
