//
// Pin.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Object holding the ID and public key of a pinned peer.  */
public struct Pin: Codable {


    public var peerID: PeerID

    public var publicKey: PublicKey

    /** True, if the pinned peer also pinned the user.  */
    public var match: Bool
    public init(peerID: PeerID, publicKey: PublicKey, match: Bool) { 
        self.peerID = peerID
        self.publicKey = publicKey
        self.match = match
    }

}
