//
// Pin.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Object holding the ID and public key of a pinned peer.  */
open class Pin: JSONEncodable {
    public var peerID: PeerID?
    public var publicKey: PublicKey?
    /** True, if the pinned peer also pinned the user.  */
    public var match: Bool?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["peerID"] = self.peerID?.encodeToJSON()
        nillableDictionary["publicKey"] = self.publicKey?.encodeToJSON()
        nillableDictionary["match"] = self.match
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
