//
// PeerID.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Unique identifier representing a specific user.  */
public typealias PinPoints = Int32
