//
// AuthenticationAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class AuthenticationAPI {
    
    /**
     Reset Sequence Number
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteAccountSecuritySequenceNumber(completion: @escaping ((_ data: Int32?,_ error: ErrorResponse?) -> Void)) {
        deleteAccountSecuritySequenceNumberWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }
    
    
    /**
     Reset Sequence Number
     - DELETE /account/security/sequence_number
     - Generates a new random sequence number, which is a per-request incrementing integer number to prevent from replay attacks. This number has to be incremented by 1 after each request.  For this call the signature can be omitted as it should only be needed if the sequence numbers of the client and the server do not match any more and therefore the client anyway cannot compute the correct signature.
     - examples: [{contentType=application/json, example="aeiou"}]
     
     - returns: RequestBuilder<String>
     */
    open class func deleteAccountSecuritySequenceNumberWithRequestBuilder() -> RequestBuilder<Int32> {
        let path = "/account/security/sequence_number"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = NSURLComponents(string: URLString)!
        
        
        let requestBuilder: RequestBuilder<Int32>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()
        
        return requestBuilder.init(method: .DELETE, url: url.url!, parameters: parameters, isValidated: false)
    }

    /**
     Request Public Key Reset
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteAccountSecurityPublicKey(completion: @escaping ((_ error: ErrorResponse?) -> Void)) {
        deleteAccountSecurityPublicKeyWithRequestBuilder().execute { (response, error) -> Void in
            completion(error);
        }
    }


    /**
     Request Public Key Reset
     - DELETE /account/security/public_key
     - Sends a random number to the user's e-mail address, which has then to be passed along when resetting the public key in the PUT variant of this request. The key is only valid for 30 minutes.
     - API Key:
       - type: apiKey peerID
       - name: peerID
     - API Key:
       - type: apiKey signature
       - name: signature

     - returns: RequestBuilder<Void>
     */
    open class func deleteAccountSecurityPublicKeyWithRequestBuilder() -> RequestBuilder<Void> {
        let path = "/account/security/public_key"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)!


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: .DELETE, url: url.url!, parameters: parameters)
    }

    /**
     Reset Public Key
     
     - parameter publicKey: (query) See PublicKey in Definitions.
     - parameter randomNumber: (query) The number sent to the user&#39;s e-mail in the delete variant of this request.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func putSecurityPublicKey(publicKey: Data, randomNumber: String, completion: @escaping ((_ data: String?,_ error: ErrorResponse?) -> Void)) {
        putSecurityPublicKeyWithRequestBuilder(publicKey: publicKey, randomNumber: randomNumber).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }
    
    
    /**
     Reset Public Key
     - PUT /account/security/public_key
     - Establishes a new public key for the user as well as a new sequence number. This request is intended to be used when the user moved to a new device. Note that the signature is optional here, as the user may has lost his phone. If it is passed, it still has to be computed with the current sequence number and private key!
     - API Key:
     - type: apiKey peerID
     - name: peerID
     - API Key:
     - type: apiKey signature
     - name: signature
     - examples: [{contentType=application/json, example="aeiou"}]
     
     - parameter publicKey: (query) See PublicKey in Definitions.
     - parameter randomNumber: (query) The number sent to the user&#39;s e-mail in the delete variant of this request.
     
     - returns: RequestBuilder<String>
     */
    open class func putSecurityPublicKeyWithRequestBuilder(publicKey: Data, randomNumber: String) -> RequestBuilder<String> {
        let path = "/account/security/public_key"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = NSURLComponents(string: URLString)!
        url.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "publicKey": publicKey,
            "randomNumber": randomNumber
        ])
        
        
        let requestBuilder: RequestBuilder<String>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()
        
        return requestBuilder.init(method: .PUT, url: url.url!, parameters: parameters)
    }

}
